--- #YAML:1.0
name:               YAML-Tiny
version:            1.43
abstract:           Read/Write YAML files with as little code as possible
author:
    - Adam Kennedy <adamk@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    File::Spec:  0.80
    Test::More:  0.47
requires:
    perl:  5.004
resources:
    bugtracker:  http://rt.cpan.org/NoAuth/ReportBug.html?Queue=YAML-Tiny
    repository:  http://svn.ali.as/cpan/trunk/YAML-Tiny
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
