---
abstract: 'Read/Write YAML files with as little code as possible'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  File::Spec: 0.80
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: YAML-Tiny
no_index:
  directory:
    - t
    - inc
requires:
  perl: 5.004
resources:
  bugtracker: http://rt.cpan.org/NoAuth/ReportBug.html?Queue=YAML-Tiny
  repository: http://svn.ali.as/cpan/trunk/YAML-Tiny
version: 1.51
