use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.006008
use Test::Spelling 0.12;
use Pod::Wordlist;


add_stopwords(<DATA>);
all_pod_files_spelling_ok( qw( bin lib  ) );
__DATA__
Adam
Kennedy
adamk
David
Golden
dagolden
Karen
Etheridge
ether
Ingy
döt
Net
ingy
James
Keenan
jkeenan
Steffen
Müller
smueller
Alexandr
Ciornii
chorny
Hilko
Bengen
bengen
Neil
Bowers
neil
Graham
Knop
haarg
Olivier
Mengué
dolmen
יובל
קוג
Yuval
Kogman
nothingmuch
github
Craig
Berry
craigberry
Slaven
Rezic
slaven
Tim
Bunce
lib
YAML
Tiny
