use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.006007
use Test::Spelling 0.12;
use Pod::Wordlist;


add_stopwords(<DATA>);
all_pod_files_spelling_ok( qw( bin lib  ) );
__DATA__
Adam
Kennedy
adamk
Alexandr
Ciornii
chorny
Craig
Berry
craigberry
David
Golden
dagolden
Graham
Knop
haarg
Hilko
Bengen
bengen
Ingy
döt
Net
ingy
James
Keenan
jkeenan
Karen
Etheridge
ether
Neil
Bowers
neil
Olivier
Mengué
dolmen
Slaven
Rezic
slaven
Steffen
Müller
smueller
Tim
Bunce
יובל
קוג
Yuval
Kogman
nothingmuch
lib
YAML
Tiny
